config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#index'
  post 'pages/location'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # reverse_geocoded_by :latitude, :longitude
  # after_validation :reverse_geocode
  geocoded_by :address
  after_validation :geocode

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:address, :latitude, :longitude])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: [:location]
  def index
    @nearbys = current_user.nearbys(20)
  end

  def location
    @resultado = "error"
    if params["latitude"].present? && params["longitude"].present?
      @resultado = Geocoder.address([params["latitude"], params["longitude"]])
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GeoG7</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if user_signed_in? %>
      <%= link_to "Salir", destroy_user_session_path, method: :delete %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/_usuarios_cercanos.html.erb
<ul>
  <h2><%= current_user.address %></h2>
  <% nearbys.each do |near| %>
    <% unless near.nil? %>
      <li><%= near.email %> - <%= (current_user.distance_from([near.latitude, near.longitude]) * 1.6) %> km. - <%= near.address %></li>
    <% end %>
  <% end %>
</ul>

app/views/pages/index.html.erb
<div id="demo"></div>
<button onclick="getLocation()">Try it</button>
<br>
<%= label_tag "latitude" %>
<%= text_field_tag "latitude" %> <br>
<%= label_tag "longitude" %>
<%= text_field_tag "longitude" %>
<br>
<button name="enviar">Obtener Dirección</button>
<br>
<div id="direccion"></div>

<hr>
<h3>Usuarios Cercanos</h3>

<%= render 'usuarios_cercanos', nearbys: @nearbys %>

<script>
  var x = document.getElementById('demo');
  function getLocation(){
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(showPosition);
    }else{
      x.innerHTML = "Geolocalización no está soportada por este navegador";
    }
  }

  function showPosition(position){
    x.innerHTML = "Latitude: " + position.coords.latitude + "<br> Longitude: " + position.coords.longitude;
    $("#latitude").val(position.coords.latitude);
    $("#longitude").val(position.coords.longitude);
  }

  $("button[name = 'enviar']").on('click', function(){
    var lat = $("#latitude").val();
    var lng = $("#longitude").val();

    $.ajax({
      url: '<%= pages_location_path %>',
      type: 'POST',
      dataType: 'script',
      data: {
        latitude: lat,
        longitude: lng
      },
    })
  });
</script>

app/views/pages/location.js.erb
$("#direccion").html("<%= j @resultado %>");
$("#user_address").val("<%= j @resultado %>");